language: c++
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
env:
  - YAML_CPP_SUPPORT_MERGE_KEYS=ON
  - YAML_CPP_SUPPORT_MERGE_KEYS=OFF
before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y \
      && sudo apt-get update -qq \
      && if [ "$CXX" == "g++" ]; then
        sudo apt-get install -qq g++-4.7 && export CXX="g++-4.7" CC="gcc-4.7"
      fi
    fi
before_script:
  - mkdir build
  - cd build
  - cmake .. -DYAML_CPP_SUPPORT_MERGE_KEYS=$YAML_CPP_SUPPORT_MERGE_KEYS
script:
  - make
  - test/run-tests

matrix:
  exclude:
  - os: linux
    compiler: clang
